name: Run the action

on:
  push:
    branches:
      - "*"

jobs:
  my_test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Code
        id: unit-tests
        run: |
          # Run your tests here and capture the result in a variable
          echo "TEST_LABEL=Passed" >> $GITHUB_OUTPUT

      - name: Set Badge Color Based on Test Result
        id: badge-color-generator
        run: |
          if [ "${{ steps.unit-tests.outputs.TEST_LABEL }}" == "Passed" ]; then
            echo badge_color="brightgreen" >> $GITHUB_OUTPUT
          else
            badge_color="red" >> $GITHUB_OUTPUT
          fi

      - name: Create and Display the Badge
        run: |
          badge="https://img.shields.io/badge/Unit_Test-${{ steps.unit-tests.outputs.TEST_LABEL }}-${{ steps.badge-color-generator.outputs.badge_color }}"
          # Read the current README content
          content=$(<README.md)
          echo "the content is $content"

          # Replace a specific placeholder with the badge, e.g., <BADGE_PLACEHOLDER>
          updated_content="${content//<UNIT_TEST_PLACEHOLDER>/$badge}"

          # Overwrite the README with the updated content
          echo "$updated_content" > README.md

          echo "the value is $badge"
          sed -i "s#<UNIT_TEST_PLACEHOLDER>#$badge#g" README.md

          echo "the new content is $content"
